### ISSUE TITLE
Cannot get default office

### ISSUE THREAD

**Issue by smoliji** [AckeeCZ/enmail#1]
after creating a default office (without any alias), i cannot get it using
```ts
enmail.getOffice()
```
because method `Expected 1 arguments, but got 0.`.

I think as it is optional at the time of the creation, it should be optional here with same default values.

**Comment by stefan-prokop-cz** [comment]
fixed https://github.com/AckeeCZ/enmail/pull/5/commits/5392fc789e588ce29ecf87f2039befece04bc558
