### ISSUE TITLE
Cannot import Mail interface directly

### ISSUE THREAD

**Issue by smoliji** [AckeeCZ/enmail#2]
In a typescript project, Mail can be only imported from dist/Mail and not directly from the package

✔️ 
```ts
import { Mail } from 'enmail/dist/Mail';
```

❌
```ts
import { Mail } from 'enmail';
```

I think the other one should be the only one working.

**Comment by smoliji** [comment]
Same for the `ServiceType`.

**Comment by stefan-prokop-cz** [comment]
fixed https://github.com/AckeeCZ/enmail/pull/5/commits/04d41c0031f49ebff8b5ae1c82e7ef2d198bb1da
